version: '2'

services:
  wed:
    image: dannalopez/as222s5_t09_be
    ports:
      - "8087:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAPIDAPI_KEY: ${RAPIDAPI_KEY} 
